---
title: "Parts we cut from Barreda & Jaeger (2025)"
output: pdf_document
date: "2025-05-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

In the appendix, we present a more fully Bayesian extension of the PSTM, the BSTM. This model performs similarly to the original PSTM---both in terms of the ability to capture listeners' perception of vowels, and in terms of estimating the uniform scaling parameter $\psi_s$. However, the BSTM has the advantage of providing the full posterior distribution over $\psi_s$ and the vowel category, allowing ideal information integration across multiple observations from the same talker. This is a critical feature for a model of speech perception as it will allow for the investigation of process of adaptation to speakers across increasing amounts of information.

## The Bayesian Sliding Template Model

The PSTM calculates MAP values of $\hat{\psi}_s$ for each vowel, and then uses the largest of these point estimates to categorize the observed formant input (@eq-criterion-psi-and-vowel). @NA07 noted that "[i]t would also be possible [...] to use a fuller Bayesian approach by integrating over the values of $\psi_s$, rather than selecting the maximum. We leave that possibility for future research" (p. 254). In order to make the methods outlined above more fully Bayesian, we can instead focus on the joint posterior distribution of $\psi_s$ and the vowel category v:

$$
P(\text{v},  \psi_s| \vec{G}) = \frac{ P(\vec{G} | \text{v}, \psi_s) \cdot P(\psi_s) \cdot P(\text{v})}{\sum_{i=i}^V \int P(\vec{G} | \text{v}_i, \psi_s) \cdot P(\psi_s) \cdot P(\text{v}_i) \, d\psi}
$$ {#eq-BSTM-posterior-joint-psi-and-vowel}

To find the posterior distribution of $\psi_s$, we marginalize over $\text{v}$:

$$
P(\psi_s | \vec{G}) = \frac{\sum_{i=1}^V  P(\vec{G} | \text{v}_i, \psi_s) \cdot P(\text{v}_i) \cdot P(\psi_s)}
{\sum_{i=1}^V \int P(\vec{G} | \text{v}_i, \psi_s) \cdot P(\psi_s) \cdot P(\text{v}_i) \, d\psi}
$$ {#eq-e20bb}

To find the posterior probabilities of different vowel categories, we marginalize over $\psi_s$:

$$
P(\text{v}_j | \vec{G}) = \frac{\int P(\vec{G} | \text{v}_j, \psi_s) \cdot P(\psi_s) \cdot P(\text{v}_j) \, d\psi}
{\sum_{i=1}^V \int P(\vec{G} | \text{v}_i, \psi_s) \cdot P(\psi_s) \cdot P(\text{v}_i) \, d\psi}
$$ {#eq-BSTM-posterior-psi-and-vowel}

Compared to focusing on MAP estimates of $\psi_s$, consideration of the posterior distribution in @eq-BSTM-posterior-joint-psi-and-vowel takes into account the uncertainty about the $\hat{\psi}_{s, \text{v}}$ for different vowel categories. This results in a model of vowel perception that is more in line with Bayesian principles, suggesting the name Bayesian Sliding Template Model (BSTM) for this version of the PSTM. By calculating the full posterior distribution of $\hat{\psi}_{s}$ rather than just MAP estimates, the BSTM allows optimal information integration across multiple vowel tokens. This will allow future work to model the iterative estimation and refinement of $\hat{\psi}_{s}$ across vowel observations, something which is not possible with the original PSTM. 

It is, of course, an empirical question whether *listeners' behavior* is better explained by this more fully Bayesian model. For the @h95 data, the BSTM performs identical to the PSTM. 

In future work we plan to expand evaluation of the BSTM in two ways. First, here we evaluated 'single-shot' implementations of methods 2, 3, and 6. That is, we did not incrementally accumulate information about $\psi_s$ across trials. For data like those in @h95, where listeners rarely hear speech from the same talker for multiple trials in a row, this is likely an acceptable simplifying assumption. However, the single-shot implementations considered here might well underestimate listeners' ability to integrate information across observations from the same talker. In future work, we thus plan to extend these methods to incrementally update the prior based on observations from the same talker [see discussion in @xie2023]. The Bayesian approach inherent in the P/BSTM is ideally suited for this purpose.

Second, the BSTM can naturally integrate the perception of indexical speaker characteristics such as age [@b_age_2018], height [@b_height_2017], or gender [@b_gender_21], via their shared reliance on $\psi_s$ [see also @kleinschmidt2018]. For example, consider the perception of some speaker characteristic $\theta$. To simultaneously estimate vowel category, $\psi_s$, *and* this new characteristic, we would add it to our model as in @eq-BSTM-joint-posterior-psi-vowel-and-indexical. This requires adding $\theta$ to the likelihood and considering joint prior of $\theta$, $\psi_s$ and vowel category. Such an approach would allow for a direct empirical comparison of different models regarding the perceptual integration of speech and social perception with relatively modest extensions of the models described here.

$$
P(\text{v},  \psi_s, \theta| \vec{G}) \propto P(\vec{G} | \text{v}, \psi_s, \theta) \cdot P(\text{v},  \psi_s, \theta)
$$ {#eq-BSTM-joint-posterior-psi-vowel-and-indexical}
